version: "3.1"
services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/ec2-user/piwigo/config:/config
      - /home/ec2-user/piwigo/gallery:/gallery
    ports:
      - 80:80
    restart: always
    networks:
      - piwigo
  piwigodb:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dasdwqdsv43r32c
      - MYSQL_DATABASE=piwigo
      - MYSQL_USER=piwigo_admin
      - MYSQL_PASSWORD=jnawdniawefiuj3209n
    volumes:
      - /home/ec2-user/mysql:/var/lib/mysql
    restart: always  
    networks:
      - piwigo
networks:
  piwigo: